export const curatedGradients = [
    {
      id: "1",
      name: "Sunset Bliss",
      type: "linear",
      colors: ["#FF6B6B", "#FFD93D"],
      direction: "to right",
      css: "linear-gradient(to right, #FF6B6B, #FFD93D)",
      tailwind: "bg-gradient-to-r from-[#FF6B6B] to-[#FFD93D]",
    },
    {
      id: "2",
      name: "Ocean Dream",
      type: "linear",
      colors: ["#4ECDC4", "#1A535C"],
      direction: "to bottom right",
      css: "linear-gradient(to bottom right, #4ECDC4, #1A535C)",
      tailwind: "bg-gradient-to-br from-[#4ECDC4] to-[#1A535C]",
    },
    {
      id: "3",
      name: "Lavender Haze",
      type: "radial",
      colors: ["#E0BBE4", "#957DAD"],
      direction: "circle at center",
      css: "radial-gradient(circle at center, #E0BBE4, #957DAD)",
      tailwind: "bg-[radial-gradient(circle_at_center,#E0BBE4,#957DAD)]",
    },
    {
      id: "4",
      name: "Forest Whisper",
      type: "linear",
      colors: ["#A8E063", "#56AB2F"],
      direction: "to top",
      css: "linear-gradient(to top, #A8E063, #56AB2F)",
      tailwind: "bg-gradient-to-t from-[#A8E063] to-[#56AB2F]",
    },
    {
      id: "5",
      name: "Cosmic Dust",
      type: "conic",
      colors: ["#2C3E50", "#FD746C", "#2C3E50"],
      direction: "from 90deg at 50% 50%",
      css: "conic-gradient(from 90deg at 50% 50%, #2C3E50, #FD746C, #2C3E50)",
      tailwind: "bg-[conic-gradient(from_90deg_at_50%_50%,#2C3E50,#FD746C,#2C3E50)]",
    },
    {
      id: "6",
      name: "Berry Burst",
      type: "linear",
      colors: ["#8A2387", "#E94057", "#F27121"],
      direction: "to right",
      css: "linear-gradient(to right, #8A2387, #E94057, #F27121)",
      tailwind: "bg-gradient-to-r from-[#8A2387] via-[#E94057] to-[#F27121]",
    },
  ]